Don't pull in wagon-file explicitly.
It conflicts with the version bundled with maven-ant-tasks.  Looks like
newer version of Leiningen create the uberjar in a different order
causing this extremetly cryptic error:

Error: org.apache.maven.wagon.providers.file.FileWagon.openConnection()V java.lang.AbstractMethodError: